I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 57, in script
    $ truth = true
  File "game/script.rpy", line 57, in <module>
    $ truth = true
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 57, in script
    $ truth = true
  File "C:\Users\Macey\Desktop\renpy-7.2.2-sdk\renpy\ast.py", line 2029, in execute
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Macey\Desktop\renpy-7.2.2-sdk\renpy\python.py", line 1954, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 57, in <module>
    $ truth = true
NameError: name 'true' is not defined

Windows-8-6.2.9200
Ren'Py 7.2.2.491
Following 1.0
Thu Apr 11 15:55:44 2019
